KidSmiley
tareqobaida/KidSmiley pull request #1
Opened 2017-02-21 20:45 UTC by Refun

2017-02-21 21:04 UTC, tareqobaida requested changes

2017-02-21 21:04 UTC, tareqobaida commented on home/templates/home/about.html
> +<!DOCTYPE html>
Follow the format from other html file. You dont have to define header and footer. Just look at other files as examples.

2017-02-21 21:04 UTC, tareqobaida commented on home/templates/home/footer.html
>      <div class="content container-fluid">
Use social icons instead of images in footer.

2017-02-22 09:36 UTC, Refun commented on home/templates/home/about.html
> +<!DOCTYPE html>
I will looking forward into the issues.

2017-02-22 09:37 UTC, Refun commented on home/templates/home/footer.html
>      <div class="content container-fluid">
Yes.please check the latest version.It's up and running with social icon!

2017-02-22 19:13 UTC, tareqobaida approved these changes

2017-02-22 19:14 UTC, merged